# Generated by Django 6.0 on 2025-12-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_web', '0002_create_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
