# Generated by Django 6.0 on 2026-01-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_web', '0003_lead_ip_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvAtmHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('trade_date', models.DateField()),
                ('spot_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('call_symbol', models.CharField(max_length=30)),
                ('call_due_date', models.DateField()),
                ('call_days_to_maturity', models.IntegerField()),
                ('call_premium', models.DecimalField(decimal_places=6, max_digits=15)),
                ('call_volatility', models.DecimalField(decimal_places=6, max_digits=10)),
                ('put_symbol', models.CharField(max_length=30)),
                ('put_due_date', models.DateField()),
                ('put_days_to_maturity', models.IntegerField()),
                ('put_premium', models.DecimalField(decimal_places=6, max_digits=15)),
                ('put_volatility', models.DecimalField(decimal_places=6, max_digits=10)),
                ('iv_atm_mean', models.DecimalField(decimal_places=6, max_digits=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iv_atm_historico',
                'indexes': [models.Index(fields=['ticker', 'trade_date'], name='iv_atm_hist_ticker_3fc6dd_idx')],
                'unique_together': {('ticker', 'trade_date')},
            },
        ),
    ]
