# Generated by Django 5.2.9 on 2026-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_web', '0004_ivatmhistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('earnings_date', models.DateField()),
                ('turno', models.CharField(choices=[('ANTES', 'Antes do mercado'), ('DEPOIS', 'Depois do mercado')], max_length=10)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'earnings_date'], name='simulador_w_ticker_ea0d07_idx')],
                'unique_together': {('ticker', 'earnings_date')},
            },
        ),
    ]
